### ISSUE TITLE
Example of drawing a parse tree when using JPEP as a library?

### ISSUE THREAD

**Issue by martinodb** [digitalheir/java-probabilistic-earley-parser#10]
Hi again,

The example of how to use JPEP as a library is for "Parser.recognize". It would be nice to add a "println" of a parse tree, just like the command-line app does.

PS: in a previous issue, I mentioned I'm struggling with CommandLine's "argument magic". What I meant is that CommanLIne draws the parse by calling "System.out.println(parse.parseTree);", where "parse" is an object of class "ParseTreeWithScore", taking the arguments to the ParseTreeWithScore form the command-line arguments in a somewhat complex way (to me, at least). So I guess the question is how to build an object of type "ParseTreeWithScore" when using JPEP as a library, given a particular grammar and a set of tokens (as you would from the command-line).

Again, thanks and regards!

**Comment by digitalheir** [comment]
Thanks, I wanted to do this but I forgot about it. I updated the readme to include an example of how to get the Viterbi parse and print it:

```java
        Parser<String> parser = new Parser<>(grammar); 
        System.out.println(
                parser.getViterbiParseWithScore(S, Tokens.tokenize("the", "stick", "chased", "the", "man")) // Most likely parse tree with probability 
        );
```
