### ISSUE TITLE
Error: "The method parse(Path, Charset) is undefined for the type Grammar"

### ISSUE THREAD

**Issue by martinodb** [digitalheir/java-probabilistic-earley-parser#9]
Hello,

I'm trying to use java-probabilistic-earley-parser as a library. Following the instructions:

```
You can parse .cfg files as follows:

Grammar<String> g = Grammar.parse(Paths.get("path", "to", "grammar.cfg"), Charset.forName("UTF-8"));

```
I get (in Eclipse) the error:
`Error: "The method parse(Path, Charset) is undefined for the type Grammar"`

I'm not using the Maven dependency, I'm just adding the latest jar to my project.

 From the command line, everything works and I get a nice parse tree based on my grammar file, but the CommandLIne class does some "magic" with the arguments and I'm struggling to figure out how to do the equivalent thing without command-line arguments.

Thanks in advance!

**Comment by digitalheir** [comment]
Oops. I changed the API but forgot to change the documentation. 

`parse` is now called [`fromString`](https://github.com/digitalheir/java-probabilistic-earley-parser/blob/master/src/main/java/org/leibnizcenter/cfg/grammar/Grammar.java#L169), to avoid confusion with [`Parser`](https://github.com/digitalheir/java-probabilistic-earley-parser/blob/master/src/main/java/org/leibnizcenter/cfg/earleyparser/Parser.java). I'll change the readme.

Thanks for spotting!
